modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "hitcolor"
version = "1.2.5"
displayName = "HitColor"
displayURL = "TG: https://t.me/ilovegamburger FunPay: alex032russ"
authors = "alex032russ"
description = '''Мод меняет цвет получения урона, на цвет который хочет пользователь, используя HEX коды цветов. Например: #FFFFFF'''

[[dependencies.hitcolor]]
modId = "forge"
mandatory = true
versionRange = "[36.2.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hitcolor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[mixin]
config = "hitcolor.mixins.json"