
#Hitcolor Configuration
[general]
	#Hit color in hex format
	color = "#C71585"
	#Transparency (0-100, where 0 is fully opaque and 100 is fully transparent)
	#Range: 0.0 ~ 100.0
	alpha = 9.999999999999998E147

